actor1_t1_end: '2022-11-07 23:59:59'
actor1_t1_start: '2022-10-18 00:00:00'
actor1_t2_end: '2022-11-17 23:59:59'
actor1_t2_start: '2022-11-11 00:00:00'
actor2_end: '2022-11-10 23:59:59'
actor2_start: '2022-11-08 00:00:00'
dataset:
  dataset_folder: data
  dataset_name: BRE
  merge_bre_cu: false
evaluation:
  batch_size: 32
  model: mtad_gat
  threshold_percentile: 99
models:
- enabled: true
  name: gdn
  params:
    heads: 1
    hidden_dim: 64
    topk: 15
- enabled: true
  name: mtad_gat
  params:
    gat_heads: 3
    gru_hidden_dim: 150
    kernel_size: 7
preprocessing:
  apply_cleaning: false
  apply_filtering: false
  downsample_freq: 3s
  val_ratio: 0.2
project_root_dir: .
seed: 42
training:
  batch_size: 32
  epochs: 50
  lr: 0.0005
  model: mtad_gat
  patience: 10
  window_size: 30
