seed: 42

# Define actor timelines
actor1_t1_start: 2022-10-18 00:00:00
actor1_t1_end: 2022-11-07 23:59:59
actor2_start: 2022-11-08 00:00:00
actor2_end: 2022-11-10 23:59:59
actor1_t2_start: 2022-11-11 00:00:00
actor1_t2_end: 2022-11-17 23:59:59

dataset:
  # path: data/sample/BREMaster-3.csv
  raw_data_path: data/raw/CUMaster2.csv
  processed_data_folder: data/processed
  window_size: 30 # set to 50 for mtad 30 for gdn

models:
  - name: "gdn"
    enabled: true
    params:
      hidden_dim: 64
      topk: 15 # previously 15
      heads: 1

  - name: "mtad_gat"
    enabled: true
    params:
      kernel_size: 7
      gru_hidden_dim: 100
      gat_heads: 2

training:
  model: gdn
  batch_size: 32
  epochs: 50
  lr: 0.0005
  patience: 10
  train_experiments_main_folder: train_experiments

evaluation:
  model: mtad_gat
  batch_size: 32
  threshold_percentile: 99
  eval_results_folder: eval_results
