# ACTOR1_END    = "2022-11-07"
# ACTOR2_START  = "2022-11-08"
# ACTOR2_END    = "2022-11-10"
# ACTOR1_RETURN = "2022-11-11"
# RESAMPLE_FREQ = "3s"

# window_slide          = 60
# in_dim                = window_slide - 1
# correlation_threshold = 0.5
# nbr_sensors           = 94
# NUM_SENSORS           = nbr_sensors
# WINDOW                = window_slide
# ALPHA                 = 0.5

seed: 42

dataset:
  # path: data/sample/BREMaster-3.csv
  path: data/raw/CUMaster.csv
  processed_folder: data/processed
  window_size: 30

training:
  batch_size: 64
  epochs: 50
  lr: 0.001

model:
  hidden_dim: 64
  topk: 15
  heads: 1

experiments_folder: experiments
