seed: 42

dataset:
  path: data/sample/BREMaster-sample2.csv
  processed_folder: content/drive/MyDrive/02_research/dyg_home/data/processed
  window_size: 10

training:
  batch_size: 64
  epochs: 1
  lr: 0.001
  # train: true

model:
  hidden_dim: 64
  topk: 15
  heads: 1

checkpoint:
  path: gdn_checkpoint50.pth
